import fs from 'node:fs';
import path from 'node:path';
import {toolRoot} from './polish.mjs';
const read=name=>JSON.parse(fs.readFileSync(path.join(toolRoot,name),'utf8'));
const report=read('polish-validation.json'),visual=read('visual-comparison.json'),geometry=read('geometry-final.json');
const khronos=read('gltf-validation.json'),replay=read('reproducibility.json');
const fmt=n=>n.toLocaleString('en-US');
const h=report.totals.high,l=report.totals.low;
const views=Object.values(visual.models).flatMap(x=>Object.values(x).flatMap(y=>Object.values(y.views)));
const primitives=Object.values(geometry.models).flatMap(x=>Object.values(x).flatMap(y=>y.primitives));
const text=[
  '# Local model polish result — 2026-09-07', '',
  'Final manifest: [models/lod/manifest.json](../../models/lod/manifest.json). All 34 high/low references use `name.<sha256 first 12>.glb`. All 17 original high files and 17 original plain-name low files remain unchanged. No browser, server, commit, push, deployment, runtime-source or handoff edit was performed by this asset task.', '',
  `High: **${fmt(h.beforeTriangles)} -> ${fmt(h.afterTriangles)} triangles** (-${fmt(h.beforeTriangles-h.afterTriangles)}; ${((1-h.afterTriangles/h.beforeTriangles)*100).toFixed(3)}%). **${fmt(h.beforeBytes)} -> ${fmt(h.afterBytes)} raw bytes** (-${((1-h.afterBytes/h.beforeBytes)*100).toFixed(2)}%). Fourteen optimized high assets; tire and both helmets are identity copies with fingerprint names. This is mostly index-width/repacking benefit; it is not measured Brotli transfer or frame-rate improvement.`, '',
  `Low: **${fmt(l.beforeTriangles)} -> ${fmt(l.afterTriangles)} triangles**, **${fmt(l.beforeBytes)} -> ${fmt(l.afterBytes)} bytes**. All old lows are retained byte-for-byte in their fingerprint copies. Larger reductions failed geometry/normal checks; passing reductions saved less than the 1% file-benefit floor.`, '',
  '| Model | High triangles: original -> final | High bytes: original -> final | Low triangles: old -> final | Low bytes: old -> final |',
  '| --- | ---: | ---: | ---: | ---: |',
];
for(const [url,r] of Object.entries(report.models))text.push(`| ${url.includes('chair')?'chair':path.basename(url,'.glb')} | ${fmt(r.high.before.triangles)} -> ${fmt(r.high.after.triangles)} | ${fmt(r.high.before.bytes)} -> ${fmt(r.high.after.bytes)} | ${fmt(r.low.before.triangles)} -> ${fmt(r.low.after.triangles)} | ${fmt(r.low.before.bytes)} -> ${fmt(r.low.after.bytes)} |`);
text.push('',
  'Verification', '',
  '- Search caps: meshoptimizer appearance error 1e-5 high / 1e-4 low, not a distance guarantee. Independent maximum-distance gates: 2e-5 high / 2e-4 low of each primitive\'s world extent; centroid interpolated-normal gates: 0.5 / 2 degrees. Node names/hierarchy, transforms, materials, original attribute tuples/UVs/images, and world bounds are preserved. World-bounds coordinate delta: 0.',
  `- [geometry-final.json](geometry-final.json): all 34 final level pairs pass. ${fmt(primitives.reduce((n,x)=>n+(x.forward?.samples||0)+(x.reverse?.samples||0),0))} bidirectional sample evaluations in compared primitives, plus direct equality checks on unchanged triangle corners. Includes all referenced vertices, face centroids and edge midpoints. Max sampled distance ${(Math.max(...primitives.map(x=>x.sampleMaxRelative))).toExponential(6)} of primitive extent; max sampled normal difference ${Math.max(...primitives.map(x=>Math.max(x.forward?.normalMaxDegrees||0,x.reverse?.normalMaxDegrees||0))).toFixed(6)} degrees. Exact matched triangles are counted as proven zero-distance samples.`,
  `- [visual-comparison.json](visual-comparison.json): ${views.length} final comparisons (17 models x high/low x 8 fixed views, 768x768), all pass. Total silhouette differences: ${views.reduce((n,x)=>n+x.silhouetteChangedPixels,0)} pixels. Max pixel-normal difference ${Math.max(...views.map(x=>x.commonPixelNormalMaxDegrees)).toFixed(6)} degrees (cap 1); max linear shade difference ${Math.max(...views.map(x=>x.commonPixelShadeMax)).toFixed(6)} (cap .01); worst shade RMSE ${Math.max(...views.map(x=>x.commonPixelShadeRMSE)).toExponential(6)} (cap .002).`,
  '- Normal/shading renders use original split normals or THREE-equivalent Float32 indexed normals, barycentric interpolation and fixed diffuse/specular lighting. Material is neutral, opaque and double-sided to inspect geometry. This does not certify website textures, PBR lighting, transmission, shadows, LOD transitions, arbitrary views or continuous surface error. Byte-identical before/after pairs reuse one rendered reference, verified by SHA256.',
  `- [gltf-validation.json](gltf-validation.json): ${khronos.totals.validatedFiles} original/final GLBs, ${khronos.totals.errors} errors, ${khronos.totals.warnings} warnings. [reproducibility.json](reproducibility.json): generator replay keeps the manifest and all ${replay.fingerprintedAssetsUnchanged} referenced assets byte-identical; all original GLBs and ${replay.backupFilesVerified} backup files match hashes.`, '',
  'Rollback evidence', '',
  '- LineFollower high: a candidate passed aggregate checks but produced a 12-pixel bottom-view normal discrepancy (max 40.97 degrees / linear shade difference .2294). The maximum-pixel gate was tightened and all its original connectivity restored. Final bottom-view difference is zero. [Rejected image](lineFollower-rejected-bottom.png); [final image](visual-comparison/lineFollower-high-bottom.png).',
  '- Chair high primitive 20 and aura high primitive 0 failed surface/normal gates and retain original geometry. Tire, both helmets, carbon-seat seam and transparent `mat_glass` parts were preserved where simplifying was unsafe or unhelpful. The tire\'s detail/lettering primitive was never decimated.',
  '- Low trials are recorded in `polish-trial-*.json` and `geometry-trial-wide-low.json`. The nearest-only trial report is diagnostic and superseded: coincident CAD faces required direct unchanged-triangle proofs before nearest-surface queries. Per-primitive decisions in selection/validation reports precede the final whole-level byte-benefit gate; `before/after` and file hashes are the authoritative final measurements.', '',
  'Key full-resolution image comparisons', '',
  '- [Steering](visual-comparison/steering-high-oblique.png), [scanner thin rods](visual-comparison/scanner-high-oblique.png), [chair](visual-comparison/ergonomic_mesh_office_chair-high-oblique.png), [tire lettering](visual-comparison/tire-hoosier-step-high-oblique.png), [guitar](visual-comparison/telecaster-high-front.png). Every model/level also has eight individual view PNGs and a contact sheet.',
  '- Manual image inspection included the linked steering/chair/tire/scanner images and LineFollower bottom before/after rollback. Numeric acceptance covers all 272 comparisons. Difference panels use 25x linear shade magnification; silhouette changes would be pink.', '',
  'Reproduction and integration details: [README.md](README.md). Exact paths, full SHA256s and stats: [polish-validation.json](polish-validation.json). Initial copy inventory: `C:/Users/oc/Desktop/WEBSITE/.codex/perf-polish-20260907/assets-before/backup-inventory.json`. Cache headers and browser verification remain with the main agent.', '');
fs.writeFileSync(path.join(toolRoot,'polish-summary.md'),text.join('\n'));
console.log('Wrote tools/lod/polish-summary.md');
