// Package verified local Cycles outputs without touching legacy release assets.
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const repo=path.resolve(__dirname,'../..');
const prefix='models/baked/realism-20260925/';
const dir=path.join(repo,prefix);
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const encoding=JSON.parse(fs.readFileSync(path.join(dir,'lighting.json')));
if(encoding.range!==16||encoding.units!=='irradiance/pi')throw Error('Unexpected bake encoding');
for(const quality of Object.values(encoding.qualities))for(const state of Object.values(quality.states)){
 if(state.clippedChannels!==0||sha(fs.readFileSync(path.join(dir,state.file)))!==state.sha256)throw Error('Bake integrity mismatch');
}
const sources={geometry:'room-baked.glb',off2k:'lightmap-off-2k.rgbm.png',on2k:'lightmap-on-2k.rgbm.png',off4k:'lightmap-off-4k.rgbm.png',on4k:'lightmap-on-4k.rgbm.png',probeOff:'probe-off.hdr',probeOn:'probe-on.hdr',deskOff:'desk-off.rgbm.png',deskOn:'desk-on.rgbm.png'};
if(sha(fs.readFileSync(path.join(dir,sources.geometry)))!==sha(fs.readFileSync(path.join(repo,'models/baked/room-baked.glb'))))throw Error('Approved room geometry changed');
const assets={version:'cycles-realism-20260925',range:16,deskBounds:[-0.925,-0.45,1.85,0.9]},records=[];
for(const [key,file] of Object.entries(sources)){
 const bytes=fs.readFileSync(path.join(dir,file)),hash=sha(bytes),ext=path.extname(file);
 const name=file.slice(0,-ext.length)+'.'+hash.slice(0,16)+ext;
 fs.writeFileSync(path.join(dir,name),bytes);assets[key]=prefix+name;
 records.push({key,path:assets[key],bytes:bytes.length,sha256:hash});
}
fs.writeFileSync(path.join(repo,'experience-baked-assets.js'),'// Content-addressed Cycles assets; generated by tools/bake/package_realism.cjs.\nexport const ROOM_BAKE = '+JSON.stringify(assets,null,2)+';\n');
const configPath=path.join(repo,'vercel.json'),config=JSON.parse(fs.readFileSync(configPath));
config.headers=config.headers.filter(x=>!x.source.startsWith('/'+prefix));
for(const r of records)config.headers.push({source:'/'+r.path,headers:[{key:'Cache-Control',value:'public, max-age=31536000, immutable'}]});
fs.writeFileSync(configPath,JSON.stringify(config,null,2)+'\n');
const initialKeys=['geometry','off2k','probeOff','deskOff'];
const report={version:assets.version,geometryPreserved:true,encoding:'RGBM16, straight RGBA8, scene-linear, no generated mipmaps',bake:{engine:'Blender 4.5.9 Cycles/OptiX',nativeResolution:4096,samples:256,diffuseBounces:6,desktopDetail:512},initialBytes:records.filter(x=>initialKeys.includes(x.key)).reduce((n,x)=>n+x.bytes,0),previousInitialBytes:7311915,assets:records};
const evidence=path.resolve(repo,'../.codex/realism-20260925');
fs.writeFileSync(path.join(evidence,'packaged-assets.json'),JSON.stringify(report,null,2)+'\n');
fs.writeFileSync(path.join(evidence,'asset-commit-files.txt'),records.map(x=>x.path).join('\n')+'\n');
console.log(JSON.stringify({files:records.length,initialBytes:report.initialBytes,reduction:1-report.initialBytes/report.previousInitialBytes}));
