// Offline, dependency-free extraction of pinned three.js r185 code.
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';

const root = new URL('./', import.meta.url);
const read = name => readFile(new URL(name, root), 'utf8');
const sha = bytes => createHash('sha256').update(bytes).digest('hex');
const files = {
  'HDRLoader.js': 'examples/jsm/loaders/HDRLoader.js',
  'DataUtils.js': 'src/extras/DataUtils.js',
  'MathUtils.js': 'src/math/MathUtils.js',
  'utils.js': 'src/utils.js',
  'constants.js': 'src/constants.js',
  'three.core.js': 'build/three.core.js',
  LICENSE: 'LICENSE',
};
const manifest = JSON.parse(await read('vendor/provenance.json'));
for (const [name, upstreamPath] of Object.entries(files)) {
  assert.equal(manifest.files[name].upstreamPath, upstreamPath);
  assert.equal(sha(await readFile(new URL(`vendor/${name}`, root))), manifest.files[name].sha256, `Vendor hash: ${name}`);
}
// Pin boundaries, retain bodies verbatim, and fail closed if the source changes.
const loader = await read('vendor/HDRLoader.js');
const parse = loader.slice(loader.indexOf('\tparse( buffer ) {'), loader.indexOf('\n\t/**\n     * Sets the texture type.'));
assert.ok(parse.startsWith('\tparse( buffer ) {') && parse.endsWith('\n\t}\n'));
const dataUtils = (await read('vendor/DataUtils.js')).replace(/^import .*;\n/gm, '').replace(/\nexport \{[\s\S]*$/, '');
const functionSource = (source, name) => {
  const start = source.indexOf(`function ${name}(`);
  assert.ok(start >= 0, name);
  const end = source.indexOf('\n}', start);
  assert.ok(end > start, name);
  return source.slice(start, end + 2);
};
const math = functionSource(await read('vendor/MathUtils.js'), 'clamp');
const utils = await read('vendor/utils.js');
const warning = 'let _setConsoleFunction = null;\n' + functionSource(utils, 'enhanceLogMessage') + '\n' + functionSource(utils, 'warn');
const constants = await read('vendor/constants.js');
const selectedConstants = ['FloatType', 'HalfFloatType', 'RGBAFormat', 'LinearFilter', 'LinearSRGBColorSpace'].map(name => {
  const match = constants.match(new RegExp(`^export (const ${name} = .*;)$`, 'm'));
  assert.ok(match, name);
  return match[1];
}).join('\n');
const service = await read('../../experience-hdr.js');
const guard = service.split('// BEGIN SHARED HEADER GUARD\n')[1]?.split('// END SHARED HEADER GUARD')[0];
assert.ok(guard?.includes('function inspectHeader('));
const license = await read('vendor/LICENSE');
const banner = `/*!\n * Generated by node tools/hdr/build.mjs; do not edit this bundle.\n * three.js r185 HDRLoader.parse, DataUtils, clamp and warning helpers.\n * Source URLs and SHA-256: tools/hdr/vendor/provenance.json\n *\n${license.split('\n').map(line => ' * ' + line).join('\n')}\n */\n`;
const bundle = banner + selectedConstants + '\n' + math + '\n' + warning + '\n' + dataUtils + '\nconst parser = { type: HalfFloatType,\n' + parse + '};\n' + guard + '\n' + await read('worker-runtime.js');
assert.ok(!/\bimport\s*(?:[({'"]|[\w*]+\s+from)/.test(bundle), 'Worker must be self-contained');
const output = new URL('../../experience-hdr-worker.js', root);
if (process.argv.includes('--check')) {
  assert.equal(await readFile(output, 'utf8'), bundle, 'Worker bundle needs regeneration');
} else {
  await writeFile(output, bundle);
}
console.log(JSON.stringify({ bundleBytes: Buffer.byteLength(bundle), sha256: sha(bundle), checked: process.argv.includes('--check') }));
